const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const GET_DOGS = "GET_DOGS";
const GET_DOG_DETAIL = "GET_DOG_DETAIL";
const GET_DOG_NAME = "GET_DOG_NAME";

export { GET_TEMPERAMENTS, GET_DOGS, GET_DOG_DETAIL, GET_DOG_NAME };
